; Michael Masterson
; E00942993
; COSC 221 Sec.0
; Lab 6
; October 30, 2014
; Write an LC-3 assembly language program to read in the
; first, middle, and the last initial of a person's name in
; lower-case characters and then display them down the left
; margin in upper-case characters.

	.ORIG x3000							; WHERE PROGRAM WILL START IN LC-3

	LEA	R0,MSG1							; LOAD MESSAGE 1
	PUTS								; DISPLAY MESSAGE 1

	GETC								; READ CHAR1
	OUT								; ECHO CHAR1
	ST	R0,CHAR1						; STORE CHAR1

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY NEW LINE

	LEA	R0,MSG2							; LOAD MESSAGE 2
	PUTS								; DISPLAY MESSAGE 2

	GETC								; READ CHAR2
	OUT								; ECHO CHAR2
	ST	R0,CHAR2						; STORE CHAR2

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY NEW LINE
	
	LEA	R0,MSG3							; LOAD MESSAGE 3
	PUTS								; DISPLAY NEW LINE

	GETC								; READ A CHAR3
	OUT								; ECHO CHAR3
	ST	R0,CHAR3						; STORE CHAR 3

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY LINE
	
	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY LINE

	LEA	R0,MSG4							; LOAD MESSAGE 4
	PUTS								; DISPLAY MESSAGE 4


	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY LINE

	LD	R0,CHAR1						; LOAD CHAR1
	LD	R2,NEG32						; LOAD NEG32
	ADD	R0,R0,R2						; CONVERT TO UPPERCASE
	OUT								; DISPLAY CHAR

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY NEW LINE

	LD	R0,CHAR2						; LOAD CHAR2
	LD	R2,NEG32						; LOAD NEG32
	ADD	R0,R0,R2						; CONVERT TO UPPERCASE
	OUT								; DISPLAY CHAR2

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY NEW LINE

	LD	R0,CHAR3						; LOAD CHAR3
	LD	R2,NEG32						; LOAD NEG32
	ADD	R0,R0,R2						; CONVERT TO UPPERCASE
	OUT								; DISPLAY CHAR3

	LD	R0,NEWLINE						; LOAD NEW LINE
	OUT								; DISPLAY NEW LINE
	
	HALT								; HALT PROGRAM

;DATA AREA
	
	NEG32	.FILL	#-32						; SUBTRACT 32 FORM CURRENT CHARACTER
	NEWLINE	.FILL	#10						; NEW LINE
	MSG1	.STRINGZ	"ENTER FIRST INITIAL. "			; MESSAGE 1
	MSG2	.STRINGZ	"ENTER MIDDLE INITIAL. "		; MESSAGE 2
	MSG3	.STRINGZ	"ENTER LAST INITIAL. "			; MESSAGE 3
	MSG4	.STRINGZ	"HERE'S THE UPPERCASE INITIALS. "	; MESSAGE 4
	CHAR1	.BLKW	1						; PLACE FOR FIRST INITIAL
	CHAR2	.BLKW	1						; PLACE FOR MIDDLE INITIAL
	CHAR3	.BLKW	1						; PLACE FOR LAST INITIAL

	.END								; END PROGRAM